### ISSUE TITLE
ModuleNotFoundError: No module named 'azua.models.bnn\\bayesianize'

### ISSUE THREAD

**Issue by ReetKaur15** [microsoft/project-azua#9]
Hi ,

while executing the azua code. I am having following error. Although the module bayesianize.py in bnn folder 

2023-08-13 18:48:32,714 train_step.py:25[INFO]Creating new model
Traceback (most recent call last):
  File "C:\Users\mkau986\.conda\envs\project-azua\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\mkau986\.conda\envs\project-azua\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\mkau986\Documents\project-azua-main\azua\run_experiment.py", line 273, in <module>
    main(sys.argv[1:])
  File "C:\Users\mkau986\Documents\project-azua-main\azua\run_experiment.py", line 269, in main
    run_experiment_on_parsed_args(args)
  File "C:\Users\mkau986\Documents\project-azua-main\azua\run_experiment.py", line 231, in run_experiment_on_parsed_args    run_experiment(
  File "C:\Users\mkau986\.conda\envs\project-azua\lib\site-packages\dependency_injector\wiring.py", line 597, in _patched
    result = fn(*args, **to_inject)
  File "C:\Users\mkau986\Documents\project-azua-main\azua\run_experiment.py", line 185, in run_experiment
    kwargs_file = azua_context.aml_step(
  File "C:\Users\mkau986\Documents\project-azua-main\azua\run_experiment.py", line 186, in <lambda>
    (lambda **kwargs: run_single_seed_experiment(ExperimentArguments(**kwargs))), pipeline_creation_mode
  File "C:\Users\mkau986\.conda\envs\project-azua\lib\site-packages\dependency_injector\wiring.py", line 597, in _patched
    result = fn(*args, **to_inject)
  File "C:\Users\mkau986\Documents\project-azua-main\azua\experiment\run_single_seed_experiment.py", line 98, in run_single_seed_experiment
    model = run_train_main(
  File "C:\Users\mkau986\Documents\project-azua-main\azua\experiment\steps\train_step.py", line 26, in run_train_main
    model = create_model(model_type, output_dir, variables, device, model_config)
  File "C:\Users\mkau986\Documents\project-azua-main\azua\models\models_factory.py", line 45, in create_model
    model_class = get_named_subclass(MODEL_BASELINE_DIRS, Model, model_name)
  File "C:\Users\mkau986\Documents\project-azua-main\azua\utils\factory_utils.py", line 55, in get_named_subclass
    subclass_list = get_subclasses(directory, parent_class)
  File "C:\Users\mkau986\Documents\project-azua-main\azua\utils\factory_utils.py", line 32, in get_subclasses
    import_module(subclass_import_path)
  File "C:\Users\mkau986\.conda\envs\project-azua\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'azua.models.bnn\\bayesianize'

(project-azua) C:\Users\mkau986\Documents\project-azua-main>

How to solve this, please help me.

**Comment by confoundry** [comment]
If you duplicate these lines (https://github.com/microsoft/project-azua/blob/639d27a6bda217ebd615d7a953a5d7ea7fad32a7/azua/utils/factory_utils.py#L29C1-L30C62) with a `"\"` rather than `"/"` that should fix it!

**Comment by ReetKaur15** [comment]
It is not working. It aga
<img width="382" alt="Capture" src="https://github.com/microsoft/project-azua/assets/138747746/e6ec25e8-8263-41e7-87c7-e0e000d0062d">
in create a new error :

**Comment by ReetKaur15** [comment]
No, It doesn't solve the problem. It again creates a new error:

<img width="382" alt="Capture" src="https://github.com/microsoft/project-azua/assets/138747746/62ecfc1a-8789-4391-a016-4cd879477c76">

**Comment by ReetKaur15** [comment]
@confoundry , It doesn't solve the problem. It again creates a new error and change the format of line when I replace  slash with "/". 
<img width="450" alt="Capture" src="https://github.com/microsoft/project-azua/assets/138747746/2611d0ed-05b9-49f4-a841-14dfedcaaf1f">


<img width="382" alt="Capture" src="https://github.com/microsoft/project-azua/assets/138747746/693bb937-cefa-42e8-8bf4-98b39970dca6">

**Comment by confoundry** [comment]
Backslash is an escape character so you need to do `"\\"` (https://stackoverflow.com/questions/28554767/how-to-use-a-string-with-backslashes-in-python)

**Comment by ReetKaur15** [comment]
@confoundry ,  Thanks it worked !. Actually , it was still creating an error:

azua.models module not found. However, when I did modification in one line. it worked !

could you please help me, as when I run the code, I want to store my imputed values in .csv file. 
All the outputs should be in run/model directory created by model, but did not get the imputed values anywhere.  I got following error either I run pvae or transformer imputer and my input does not contain any target values. **I want to impute missing chunk values in my data .csv file**
<img width="656" alt="Capture" src="https://github.com/microsoft/project-azua/assets/138747746/36ad43ac-f698-49ed-9704-95edcb217fcf">

It would be great if you help.

Thanks
